---
title: "R package review"
description: |
  Welcome to 5523 assignment blog.This blog will talk about R package review.
author:
  - name: DIYAO CHEN 
    
date: 10-24-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


# Introduction
This blog will review Dewi Amaliah's R package. 



# Package
This package is name c19euxplorer, and It includes a shiny app in the package. This package and app are focused on exploring the data of COVID19 related variables in various countries in Europe.


# What did it do?
In the shiny app, which is included different 6 pages, and it discusses the different situation of COVID19 in Europe. 

In the cases and deaths page provide case and cases per 10000 people, deaths and deaths per 10000 people research in it. We can clearly see the monthly change in quantity. and it gives a detailed explanation. The line chart is a good example of that.

The testing page provides compared 3 different countries (Austria, Italy and Spain). The clear line chart we can see the change.

In the tracing page, we can select a different country to know the transmission of COVID19 in Europe's different country by week. the bar chart shows a different way of route of transmission.On the down of the left side, 
We can see where the country is in Europe.

For the data page, it has two DT table to Summarize all the data.

overall, the shiny app is successful, It gives a clear picture of the state of the COVID19 in Europe. It explores the total case with death rate, the weekly testing rate, different country transmission by week and compares every country, which let visitors can get a full picture of the COVID19 situation in Europe.

# Are the improvements that could be made to the code? Are there improvements that could be made to the shiny app inside the package?

For the package:
When I run the app(launch_app), I meet some problem. The package tidycovid19 is inside the app, but I can not install it. So, I use all day to overcome this problem. Maybe you can delete this package replace to the CSV file for input the raw data.


For the shinyapp:
1. It should add a custom colour for each country in the plots in “Cases and Death” and the “Testing” tab. because, all the country is the same colour now, maybe hard to observe the difference.

2.The x-axis label sequence in the daily-wise plots is still by three months.  should have changed it into monthly. Because of I want to check February, but it is not shown on the plot.


# what you’ve learned from reviewing the package?
The developers show to give more guidance to the visitor. More explain can be given the visitor more guide and how to use the package easily rather than the visitor use it for no purpose. On the other hand, the content inside the package can be better used. The clear guide is important.


# Appendix

### Documentation

The package includes all the following forms of documentation:

- [✔] **Installation instructions:** for the package is found in README  
- [✔] **Vignette(s)** demonstrating major functionality that runs successfully locally  
- [✔] **Function Documentation:** for all exported functions in R help  
- [✔] **Examples** for all exported functions in R Help that run successfully locally  


#### Comments

- **Installation instructions :** The `readme` provides detailed installation instructions, which can let the users install it successfully. 
<br>

- **Vignette(s) :** The Vignette page provides comprehensive information for the major functions and the usage of the built-in Shiny app.  

<br>
- **Function Documentation :** All exported functions in R help with nice documentation.  

<br>
- **Examples : ** All exported examples in R help can run successfully.  


### Functionality

- [✔] **Installation:** Installation succeeds as documented.  
<br>

- [✔] **Functionality:** Any functional claims of the software been confirmed.  
<br>

- [✔] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine.